package http

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/rs/zerolog/log"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/vincehamel81-dot/deckforge/config"
	_ "github.com/vincehamel81-dot/deckforge/docs" // generated by swag init
	"github.com/vincehamel81-dot/deckforge/internal/domain/game"
	"github.com/vincehamel81-dot/deckforge/internal/domain/player"
	"github.com/vincehamel81-dot/deckforge/internal/domain/shoe"
	"github.com/vincehamel81-dot/deckforge/internal/domain/user"
	ws "github.com/vincehamel81-dot/deckforge/internal/infrastructure/ws"
	"github.com/vincehamel81-dot/deckforge/internal/presentation/http/handlers"
	"github.com/vincehamel81-dot/deckforge/internal/presentation/http/middleware"
)

func NewRouter(
	cfg *config.Config,
	games game.Repository,
	players player.Repository,
	shoes shoe.Repository,
	users user.Repository,
	hub *ws.Hub,
) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	r := gin.New()

	r.Use(corsMiddleware(cfg.CORSOrigin))
	r.Use(middleware.CorrelationMiddleware())
	r.Use(middleware.LoggerMiddleware())
	r.Use(gin.Recovery())

	jwtExpiry, _ := time.ParseDuration(cfg.JWTExpiry)
	if jwtExpiry == 0 {
		jwtExpiry = 24 * time.Hour
	}

	authH := handlers.NewAuthHandler(users, cfg.JWTSecret, jwtExpiry, cfg.MaxUsernameLength)
	gameH := handlers.NewGameHandler(games, players, shoes, users, hub, cfg.AutoEndGame)
	shoeH := handlers.NewShoeHandler(games, shoes, hub)
	playerH := handlers.NewPlayerHandler(games, players, shoes, hub)
	dealH := handlers.NewDealHandler(games, players, shoes, hub, cfg.AutoEndGame)
	wsH := handlers.NewWSHandler(hub, games, cfg.JWTSecret)

	auth := middleware.AuthMiddleware(cfg.JWTSecret)
	dealer := middleware.DealerMiddleware(games)

	// Public routes
	r.POST("/auth/register", authH.Register)
	r.POST("/auth/login", authH.Login)
	r.GET("/health", func(c *gin.Context) { c.JSON(200, gin.H{"status": "ok"}) })
	r.POST("/decks", shoeH.CreateDeck)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Debug routes — controlled by DEBUG_ENABLED env var (default false).
	// Safe to enable in production: set DEBUG_ENABLED=true and DEBUG_TOKEN=<secret>.
	// When DEBUG_TOKEN is set, every /debug/* request must carry X-Debug-Token: <secret>.
	if cfg.DebugEnabled {
		debugGroup := r.Group("/debug", debugTokenMiddleware(cfg.DebugToken))
		debugGroup.GET("/error", func(c *gin.Context) {
			log.Error().
				Str("correlationId", middleware.CorrelationID(c)).
				Str("component", "debug").
				Msg("simulated application error — triggered via /debug/error")
			c.JSON(http.StatusInternalServerError, gin.H{"error": "SIMULATED_SERVER_ERROR"})
		})
		debugGroup.GET("/warn", func(c *gin.Context) {
			log.Warn().
				Str("correlationId", middleware.CorrelationID(c)).
				Str("component", "debug").
				Msg("simulated warning — triggered via /debug/warn")
			c.JSON(http.StatusOK, gin.H{"status": "warning logged"})
		})
	}

	// Authenticated game routes
	g := r.Group("/games", auth)
	{
		g.POST("", gameH.CreateGame)
		g.GET("", gameH.ListGames)
		g.GET("/:id", gameH.GetGame)
		g.DELETE("/:id", gameH.DeleteGame) // auth check in command (dealer or admin)
		g.POST("/:id/start", dealer, gameH.StartGame)
		g.POST("/:id/end", dealer, gameH.EndGame)

		g.POST("/:id/shoe/decks", dealer, shoeH.AddDeckToShoe)
		g.POST("/:id/shoe/shuffle", dealer, shoeH.ShuffleShoe)
		g.GET("/:id/shoe/suits", shoeH.GetSuitCounts)
		g.GET("/:id/shoe/cards", shoeH.GetCardCounts)

		g.POST("/:id/players", playerH.JoinGame)
		g.DELETE("/:id/players/:pid", playerH.LeaveGame)
		g.GET("/:id/players", dealH.GetLeaderboard)

		g.POST("/:id/players/:pid/deal", dealer, dealH.DealCards)
		g.POST("/:id/deal-round", dealer, dealH.DealRound)
		g.GET("/:id/players/:pid/hand", dealH.GetPlayerHand)
	}

	// WebSocket outside the auth group — browsers cannot send Authorization headers
	// on WS upgrades. The handler validates the JWT from ?token= itself.
	r.GET("/games/:id/ws", wsH.ServeWS)

	return r
}

// debugTokenMiddleware rejects requests that do not carry the expected
// X-Debug-Token header. It is a no-op when token is empty (dev convenience).
func debugTokenMiddleware(token string) gin.HandlerFunc {
	return func(c *gin.Context) {
		if token != "" && c.GetHeader("X-Debug-Token") != token {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "debug token required"})
			return
		}
		c.Next()
	}
}

func corsMiddleware(origin string) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", origin)
		c.Header("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Authorization,Content-Type,X-Correlation-ID")
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}
		c.Next()
	}
}
